School_classes
rasha-saber/laravel-R6 pull request #1
Opened 2024-07-21 04:57 UTC by rasha-saber

2024-07-21 08:44 UTC, Nora-Lootfy approved these changes
nice work,, a little hint try to open pull request after your first pushing commit to github

2024-07-23 22:41 UTC, Nora-Lootfy requested changes
good job ya Rasha

2024-07-23 22:41 UTC, Nora-Lootfy commented on app/Http/Controllers/SchoolClassController.php
> +'price' =>($request->price),
why you add `()` no need for these

2024-07-23 22:41 UTC, Nora-Lootfy commented on app/Http/Controllers/SchoolClassController.php
> +    $data=[
try to format your code ya Rasha

2024-07-24 13:58 UTC, rasha-saber commented on app/Http/Controllers/SchoolClassController.php
> +    $data=[
اوك تمام شكرا لحضرتك

2024-07-24 13:59 UTC, merged